### PR TITLE
Koppor PRs

### PR DESCRIPTION
**Pull request by mhelvens**
This is a combination of #13, #14, #15, #17, #18 and #19. All those separate PRs were getting difficult to manage. I'll also clean up a bit and make everything somewhat consistent.

### CODE REVIEW

**Comment by mhelvens** [comment]
@koppor: Please have a look at this and let me know if you're OK with the changes. Note that I had to remove the `fontspec` rule, because that package requires XeLaTeX or LuaTeX, excluding most users. :-)

**Comment by koppor** [comment]
Looks good!

Only question regarding `fontspec`: doesn't say `if loaded` that if package X is loaded, load it after package Y?

So:

    \Load {fontspec} after  {amsmath,amsfonts,amssymb}
                     if loaded

means

In case there is a `\usepackage{fontspec}` existing, move it to a place after `\usepackage{amsmath,masfonts,amssymb}`. In case there is no `\usepackage{fontspec}`, do not do anything.

**Comment by mhelvens** [comment]
But you had a rule that said `always`: https://github.com/mhelvens/latex-pkgloader/pull/13/files#diff-47339fb628fbda61d3fd418e86e4bcf9R192

**Comment by koppor** [comment]
Ah, yes, I see. Oh, difficult thing. `selnolig` only works with fontspec.

Current solution:

```
\Load {fontspec} before {selnolig}
                 always
                 because {selnolig depends on fontspec}
```

With the current setup, the `always` should be exchanged by `if loaded` so that the user has to know if he loads `selnolig`, he has to add `fontspec`?

Can I express "If selnoloig is loaded, also load fontspec"?

**Comment by mhelvens** [comment]
Yes, with `if {selnolig}`. But if it's a dependency, why doesn't `selnolig` load it itself?

**Pull request merged**
